# -*- coding: utf-8 -*-
"""Aula29-32_Facede.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sl_AiaGPq3DWLV4Vgkreu4r1XWmcIX3i

# **Exemplo Classe FACEDE: Cria uma Interface simplificada para muitas outras classes**
"""

class ColetarDados:  #Subsistema 1
    def coletar(self):
        print("Coletando Dados...")

class LimparDados:  #Subsistema 2
    def limpar(self):
        print("Limpando Dados...")

class TransformarDados:  #Subsistema 3
    def transformar(self):
        print("Transformando Dados...")

class MontarDW:  #Subsistema 7
    def montarDw(self):
        print("Criando Data Warehouse...")

class PrepararModelo:  #Subsistema 4
    def preparar(self):
        print("Selecionando Modelos...")

class ExecutarModelo:  #Subsistema 5
    def executar(self):
        print("Executando Algoritmos...")

class VerificarResultados:  #Subsistema 6
    def verificar(self):
        print("Verificando Resultados...")

class ProjetoAssistente:  #Facade
    def __init__(self):
        self.coleta = ColetarDados()
        self.limpeza = LimparDados()
        self.transformacao = TransformarDados()
        self.montaDw = MontarDW()
        self.preparo = PrepararModelo()
        self.execucao = ExecutarModelo()
        self.verificacao = VerificarResultados()

    def iniciarAssistente(self): #E SE EU QUISER APENAS UM DATAWAREHOUSE?
        self.coleta.coletar()
        self.limpeza.limpar()
        self.transformacao.transformar()
        self.montaDw.montarDw()
        self.preparo.preparar()
        self.execucao.executar()
        self.verificacao.verificar()


assistente = ProjetoAssistente()
assistente.iniciarAssistente()

class ProjetoETL:  #Facade
    def __init__(self):
        self.coleta = ColetarDados()
        self.limpeza = LimparDados()
        self.transformacao = TransformarDados()
        self.montaDw = MontarDW()

    def iniciarETL(self): #MONTANDO O DATAWAREHOUSE
        self.coleta.coletar()
        self.limpeza.limpar()
        self.transformacao.transformar()
        self.montaDw.montarDw()

etl = ProjetoETL()
etl.iniciarETL()