# -*- coding: utf-8 -*-
"""Aula33-36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ITsL0x3LO_EGE6yjrePNiewjWOaz7pA

# **Exemplo de uso do Flask no Colab**

**Ngrok** é uma ferramenta utilizada para criar túneis seguros para se conectar com aplicativos locais. Com ele, você pode compartilhar aplicativos locais com outras pessoas pela internet.

**Pyngrok** é uma biblioteca Python utilizada para criar e gerenciar túneis **ngrok**. Dessa forma, é possível (e simples) apresentar os aplicativos Flask na internet (mas o Colab tem um limite de uso de 12h).
"""

#Primeiro passo: Instalar o pyngrok
#!pip install flask-ngrok pyngrok
!pip install flask-ngrok
!pip install pyngrok==7.1.2
# !pip install Flask==3.0.0 pyngrok==7.1.2

#Segundo passo: Criar conta e obter token em ngrok
# https://ngrok.com/

# Obtenha o Token 'Seu Token' menu Setup & Installation
# !ngrok authtoken 'Seu Token'

!ngrok authtoken 2nnSaPsqm7ZokbiaifSZXLK7VFz_4BAEnzJbGsfMVQnVdEkcS

from flask import Flask
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app) # Inicia o servidor e a conexão com o ngrok

@app.route("/")
def home():
   pagina = ("<h1>Exemplo de uso de Flask no Colab!</h1> <br><br>"
   + "<a href=\"autenticar\">Clique aqui para se autenticar</a>")
   return pagina

@app.route("/autenticar")
def autenticar():
   formulario = ( "<form method=\"get\" action=\"autenticado\">"
   + "<h1>Login</h1> "
   + "<p> <label for=\"nome\">Nome</label>"
   + "    <input type=\"text\" placeholder=\"Seu Nome\"/></p>"
   + "<p> <label for=\"senha\">Senha</label>"
   + "    <input type=\"password\" placeholder=\"Sua Senha\" /></p>"
   + "<p> <input type=\"submit\" value=\"Autenticar\" /> &nbsp"
   + "    <input type=\"reset\" value=\"Limpar Campos\" /></p>"
   + "</form>" )
   return formulario

@app.route("/autenticado")
def autenticado():
   pagina =  ("<h1>Usuário autenticado com sucesso!</h1>"
   + "<a href=\"/\">Home</a>")
   return pagina

app.run()