# -*- coding: utf-8 -*-
"""Aula29-32_Observer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHgZocB_k-6mReNbDq0PpFjCkMlWW22y

# **Exemplo Classe OBSERVER: Cria uma classe para interessados receberem notificações/atualizações de outros objetos**
"""

class Assinante:

    def __init__(self, name):
        self.name = name

    def update(self, message):
        print('{} recebeu a mensagem: "{}"'.format(self.name, message))

class Publicador:

    def __init__(self):
        self.assinantes = set()

    def subscribe(self, assin):
        self.assinantes.add(assin)

    def unsubscribe(self, assin):
        self.assinantes.discard(assin)

    def notify(self, message):
        for assinante in self.assinantes:
            assinante.update(message)

pub = Publicador()

jose = Assinante('Jose')
maria = Assinante('Maria')

pub.subscribe(jose)
pub.subscribe(maria)

pub.notify("Hora da aula!")
pub.unsubscribe(jose) #Jose fez bagunça, perdeu o recreio, foi para a direção
pub.notify("Hora do recreio, mas surigo estudar!")
pub.notify("Hora da voltar para a sala!")
pub.subscribe(jose) #Jose foi punido, ficou na sala da diretora até acabar a aula :)
pub.notify("Hora de ir para casa!")