# -*- coding: utf-8 -*-
"""Aula25-28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_uZLJS7dFt5Bke_Yx8agVVKZkF7hVoxl

# **Exemplo Classe SINGLETON: Cria uma Única Instância**
"""

class Singleton:

    __instance = None

    #cls - refere-se à classe, self - refere-se à instância
    #__new__ é chamado primeiro para retornar uma nova instancia da sua classe
    #__new__ é construtor implícito - CHAMADO QUANDO PRECISA MUDAR A CONSTRUÇÃO DO OBJETO
    #__init__ é chamado após o __new__ para iniciar as variáveis e não retorna instância
    def __new__(cls, param1, param2):
        if cls.__instance is None:
            print('**********    NEW SINGLETON OBJECT WAS CREATED!    **********')
            cls.__instance = object.__new__(cls) #__new__(cls) cria uma instância da classe
            cls.__instance.atrib1 = param1
            cls.__instance.atrib2 = param2
        return cls.__instance

    def __init__(self, param1, param2): #Construtor feito para não alterar a instância.
        print('*The initialization was completed!*')

    #__call__ permite que a instância seja invocada como um método
    def __call__(cls, *args, **kwargs):
        print(f"O singleton criado tem o atrib1 igual a: {cls.__instance.atrib1}")
        #Exemplo args e kwargs: https://www.youtube.com/watch?v=4jBJhCaNrWU
        #O que importa são os asteriscos e não o nome args e kwargs (kw = keyword arguments)

#TESTE DE INSTANCIAÇÕES
sngl1 = Singleton('Dom Pedro 2', 'true')
sngl1() #Invoca o método call
sngl2 = Singleton('Tiradentes', 'sem rosto')
sngl3 = Singleton('Deodoro da Fonseca', 'NaN')
print('TESTE:  atrubuto 1: ' + sngl1.atrib1) #note que o atributo impresso foi da "instanciação" de sngl2
print('TESTE:  atrubuto 2: ' + sngl2.atrib2) #note que o atributo impresso foi da "instanciação" de sngl2
sngl2() #Invoca o método call
sngl1() #Invoca o método call
sngl3() #Invoca o método call
print(sngl1)
print(sngl2)
print(sngl3)